### PR TITLE
fix: issue swift 5

### PR DESCRIPTION
**Pull request by riderx**
related to https://github.com/epicshaggy/capacitor-native-biometric/pull/47
with just what is needed

### CODE REVIEW

**Comment by gbkwiatt** [comment]
Can we get that merged please ?

**Comment by antonio-masotti** [comment]
Something new here? 

This issue is impeding our deployment since almost two weeks :-(

**Comment by riderx** [comment]
@epicshaggy please?

**Comment by riderx** [comment]
I close this, it has been merged in other PR : 
https://github.com/epicshaggy/capacitor-native-biometric/pull/52

**Pull request closed without merging**
